"use client";

import * as React from "react";
import { cn } from "../lib/utils";

export interface NoiseDisplacementProps extends React.HTMLAttributes<HTMLDivElement> {
  children?: React.ReactNode;
  /** Grain opacity, 0 to 1. */
  intensity?: number;
  /** Grain scale. Higher is finer. */
  frequency?: number;
  /** Drift the grain instead of holding it still. */
  animate?: boolean;
}

/**
 * A film grain laid over a surface.
 *
 * The grain is generated by an inline SVG `feTurbulence` rather than a tiled PNG,
 * so it never repeats visibly, costs no request, and scales to any size. It sits
 * in an overlay with `pointer-events: none` and is hidden from assistive
 * technology, so it can never intercept input or be announced.
 */
export const NoiseDisplacement = React.forwardRef<HTMLDivElement, NoiseDisplacementProps>(
  ({ className, children, intensity = 0.32, frequency = 0.85, animate = false, style, ...props }, ref) => {
    const id = React.useId().replace(/:/g, "");
    return (
      <div
        ref={ref}
        data-open-ui="noise-displacement"
        data-animate={animate || undefined}
        className={cn("oui-noise", className)}
        style={{ "--oui-noise-intensity": intensity, ...style } as React.CSSProperties}
        {...props}
      >
        {children}
        <svg className="oui-noise__grain" aria-hidden="true" focusable="false">
          <filter id={`${id}-grain`}>
            <feTurbulence type="fractalNoise" baseFrequency={frequency} numOctaves={3} stitchTiles="stitch" />
            <feColorMatrix type="saturate" values="0" />
          </filter>
          <rect width="100%" height="100%" filter={`url(#${id}-grain)`} />
        </svg>
      </div>
    );
  },
);
NoiseDisplacement.displayName = "NoiseDisplacement";
